In [3]:
import numpy as np

In [13]:
my_list=[1,2,3,4,5]

In [14]:
print(my_list)

[1, 2, 3, 4, 5]


In [15]:
arr=np.array(my_list)

In [16]:
arr

array([1, 2, 3, 4, 5])

In [17]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [18]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [21]:
np.zeros(3)

array([0., 0., 0.])

In [22]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [25]:
np.linspace(0,5,100) #two adjacent elements have same diff 3rd arg is no of argyument /size of array ,first two are start and end

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [26]:
np.eye(4) #gets diagnoal element ones

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
np.random.rand(5)

array([0.0288625 , 0.21110662, 0.95605128, 0.03509701, 0.1387307 ])

In [28]:
np.random.rand(5,5)

array([[0.50719462, 0.07872087, 0.37659567, 0.41810119, 0.73245155],
       [0.5284461 , 0.59339127, 0.71815832, 0.85561238, 0.6494268 ],
       [0.36675607, 0.09641937, 0.79806752, 0.02153981, 0.88459397],
       [0.50255418, 0.79608936, 0.19071495, 0.3853618 , 0.62141227],
       [0.52583087, 0.82060451, 0.9406035 , 0.68118434, 0.93258364]])

In [30]:
np.random.randn(2,3) #distributed unformly something will see in data vizualise

array([[-0.45772944,  0.46715612,  0.96041546],
       [-1.00213968,  1.79580678,  0.64255436]])

In [31]:
np.random.randint(1,100)

91

In [33]:
randarrInt=np.random.randint(1,100,10) #[1,100)

In [34]:
randarrInt

array([13, 12, 43, 58, 56, 52, 46, 87, 36, 77])

In [35]:
randarrInt.reshape(2,5)

array([[13, 12, 43, 58, 56],
       [52, 46, 87, 36, 77]])

In [36]:
randarrInt.max()

np.int64(87)

In [37]:
randarrInt.min()

np.int64(12)

In [38]:
randarrInt.argmax() #max value index

np.int64(7)

In [39]:
randarrInt.argmin()

np.int64(1)

In [44]:
randarrInt.shape

(10,)

In [45]:
randarrInt.reshape(2,5).shape

(2, 5)

In [46]:
randarrInt.dtype #returns datatype in your array

dtype('int64')

In [47]:
arr=np.arange(0,11)

In [48]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
arr[3]

np.int64(3)

In [50]:
arr[0:7]

array([0, 1, 2, 3, 4, 5, 6])

In [51]:
arr[0:5]=100

In [52]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [53]:
arr=np.arange(0,11)

In [54]:
arr1=arr[0:5]

In [55]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
arr1

array([0, 1, 2, 3, 4])

In [57]:
arr1[:]=99

In [58]:
arr1

array([99, 99, 99, 99, 99])

In [59]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [60]:
arr=np.arange(0,11)

In [61]:
arr1=arr.copy()

In [62]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
arr1[:]=100

In [66]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
arr1

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [68]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [69]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
arr_2d[1]

array([4, 5, 6])

In [75]:
arr_2d[1][2]

np.int64(6)

In [76]:
arr_2d[1,2] #use this instead of above

np.int64(6)

In [78]:
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [79]:
arr=np.arange(0,11)

In [80]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [82]:
bool_arr=arr>5

In [83]:
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [84]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [85]:
arr[arr<3]

array([0, 1, 2])

In [86]:
arr=np.arange(0,11)

In [87]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [88]:
arr+10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [89]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [90]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [91]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [92]:
arr*10

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [93]:
arr-10

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0])

In [94]:
arr/2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [95]:
arr/arr #frst element is 0 so it will give warning and return nan instead of 0/0 others wokrs good and 1/0 = infinty(inf)

/var/folders/g3/gpqvbl0d2szgrjfrtvj0jhn40000gn/T/ipykernel_87912/3208292755.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr #frst element is 0 so it will give warning and return nan


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [96]:
1/arr

/var/folders/g3/gpqvbl0d2szgrjfrtvj0jhn40000gn/T/ipykernel_87912/255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [97]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [100]:
np.exp(arr) #expoenetal

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [101]:
np.max(arr)

np.int64(10)

In [102]:
arr.max()

np.int64(10)

In [103]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])